const $=s=>document.querySelector(s),C=$('#canvas'),ctx=C.getContext('2d');
let art=null,raf=0; const durationMs=()=>Number($('#duration').value)*1000;
function key(){return localStorage.getItem('gemini_api_key')||''}
function status(s,e=false){$('#status').textContent=s;$('#status').style.color=e?'#ff8178':''}
function openApi(){$('#apiKey').value=key();$('#apiDialog').showModal()}
function blank(){ctx.fillStyle='#020202';ctx.fillRect(0,0,406,720);ctx.strokeStyle='#292929';ctx.strokeRect(18,18,370,684);ctx.fillStyle='#777';ctx.font='15px Pretendard,sans-serif';ctx.textAlign='center';ctx.fillText('그리고 싶은 것을 입력하세요',203,360)}
function hash(x,y){let n=(x*374761393+y*668265263)^0x5bf03635;n=(n^(n>>13))*1274126177;return((n^(n>>16))>>>0)/4294967295}
function draw(progress=1){ctx.fillStyle='#020202';ctx.fillRect(0,0,406,720);if(!art)return blank();let p=Math.max(0,Math.min(1,progress)),w=art.width,h=art.height,scale=Math.min(370/w,600/h),dw=w*scale,dh=h*scale,dx=(406-dw)/2,dy=(720-dh)/2;ctx.save();ctx.beginPath();ctx.rect(18,82,370,574);ctx.clip();if(p>=.999){ctx.drawImage(art,dx,dy,dw,dh)}else{let cols=34,rows=55,cw=dw/cols,ch=dh/rows;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){let sweep=(y/rows)*.48+(x/cols)*.12,random=hash(x,y)*.4;if(sweep+random<p){ctx.drawImage(art,x/cols*w,y/rows*h,w/cols+1,h/rows+1,dx+x*cw,dy+y*ch,cw+1,ch+1)}}}ctx.restore()}
function animate(){cancelAnimationFrame(raf);$('#playBtn').hidden=true;let start=performance.now(),d=durationMs();function frame(now){let t=now-start;draw(t/d);if(t<d)raf=requestAnimationFrame(frame);else{$('#playBtn').hidden=false;draw(1)}}raf=requestAnimationFrame(frame)}
async function callImage(subject){let prompt=`Draw exactly this subject: "${subject}". A recognizable, elegant hand-drawn monochrome pencil/chalk line illustration on a pure black background. Thin warm-gray imperfect lines, subtle cross-hatching only where useful, strong silhouette, centered single composition, generous empty space, vertical 9:16 canvas. If it is a person, accurately show every described physical feature, expression, pose and especially facial hair. If it is an object or symbol, draw that exact object clearly. No border, no caption, no letters, no watermark, no UI, no photorealism, no color.`;let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-image:generateContent?key=${encodeURIComponent(key())}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:['IMAGE'],imageConfig:{aspectRatio:'9:16',imageSize:'1K'}}})}),j=await r.json();if(!r.ok)throw Error(j.error?.message||'이미지 생성 실패');let part=j.candidates?.[0]?.content?.parts?.find(v=>v.inlineData?.data);if(!part)throw Error('이미지 응답이 없습니다. 이 API 키에서 이미지 모델을 사용할 수 있는지 확인하세요.');return new Promise((ok,no)=>{let img=new Image;img.onload=()=>ok(img);img.onerror=()=>no(Error('생성 이미지를 읽지 못했습니다.'));img.src=`data:${part.inlineData.mimeType||'image/png'};base64,${part.inlineData.data}`})}
async function make(){let subject=$('#script').value.trim();if(!subject)return status('그리고 싶은 대상을 입력하세요.',true);if(!key())return openApi();status('입력한 대상을 손그림으로 그리고 있습니다…');$('#makeBtn').disabled=$('#regenerateBtn').disabled=true;try{art=await callImage(subject);$('#previewBtn').disabled=$('#downloadBtn').disabled=$('#regenerateBtn').disabled=false;status('그림이 완성되었습니다. 마음에 들지 않으면 그림만 다시 생성하세요.');animate()}catch(e){status(e.message,true)}finally{$('#makeBtn').disabled=false;if(art)$('#regenerateBtn').disabled=false}}
async function tts(){if($('#voice').value==='none')return null;let sec=$('#duration').value,r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-tts-preview:generateContent?key=${encodeURIComponent(key())}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`다음 문장을 자연스럽게 ${sec}초 안에 읽어주세요. ${$('#script').value.trim()}`}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:$('#voice').value}}}}})}),j=await r.json();if(!r.ok)return null;let part=j.candidates?.[0]?.content?.parts?.find(p=>p.inlineData);if(!part)return null;let bin=Uint8Array.from(atob(part.inlineData.data),c=>c.charCodeAt(0)),ac=new AudioContext(),pcm=new Int16Array(bin.buffer),buf=ac.createBuffer(1,pcm.length,24000),data=buf.getChannelData(0);for(let i=0;i<pcm.length;i++)data[i]=pcm[i]/32768;let src=ac.createBufferSource(),dest=ac.createMediaStreamDestination();src.buffer=buf;src.connect(dest);src.connect(ac.destination);return{src,stream:dest.stream}}
async function download(){if(!art)return;let sec=$('#duration').value;status(`${sec}초 영상을 녹화하고 있습니다…`);$('#downloadBtn').disabled=true;try{let au=await tts().catch(()=>null),cs=C.captureStream(30),stream=new MediaStream([...cs.getVideoTracks(),...(au?au.stream.getAudioTracks():[])]),types=['video/mp4;codecs=h264,aac','video/webm;codecs=vp9,opus','video/webm'],mime=types.find(MediaRecorder.isTypeSupported)||'',rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:5000000}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);let done=new Promise(r=>rec.onstop=r);rec.start();if(au)au.src.start();animate();await new Promise(r=>setTimeout(r,durationMs()+180));rec.stop();await done;let blob=new Blob(chunks,{type:rec.mimeType}),ext=rec.mimeType.includes('mp4')?'mp4':'webm',a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`science-sketch-${sec}s.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);status(`${ext.toUpperCase()} 영상이 다운로드되었습니다.`)}catch(e){status('녹화 실패: '+e.message,true)}finally{$('#downloadBtn').disabled=false}}
$('#apiBtn').onclick=openApi;$('#saveApi').onclick=()=>{localStorage.setItem('gemini_api_key',$('#apiKey').value.trim());status('API 키를 저장했습니다.')};$('#makeBtn').onclick=$('#regenerateBtn').onclick=make;$('#previewBtn').onclick=$('#playBtn').onclick=animate;$('#downloadBtn').onclick=download;blank();
