const $=s=>document.querySelector(s),C=$('#canvas'),ctx=C.getContext('2d');
let scene=null,raf=0; const durationMs=()=>Number($('#duration').value)*1000;
const fallback={title:'과학은 연결하는 일',english:'Science connects what we observe.',objects:[{type:'person',x:200,y:370,scale:1},{type:'atom',x:105,y:270,scale:.8},{type:'flask',x:300,y:300,scale:.8}],strokes:[{points:[[105,270],[155,315],[200,280],[250,320],[300,300]],width:1.2,opacity:.7}],accent:'pulse'};
const icons={atom:[[[-35,0],[35,0]],[[-18,-30],[18,30]],[[-18,30],[18,-30]]],flask:[[[-12,-40],[-12,-8],[-34,38],[34,38],[12,-8],[12,-40]],[[-18,12],[20,12]]],beaker:[[[-28,-36],[-22,36],[22,36],[28,-36]],[[-28,-36],[28,-36]],[[-20,12],[20,12]]],testtube:[[[-13,-40],[-13,25],[0,40],[13,25],[13,-40]],[[-15,-40],[15,-40]]],dna:[[[-24,-42],[24,42]],[[-24,42],[24,-42]],[[-17,-27],[17,-27]],[[-22,-9],[22,-9]],[[-22,10],[22,10]],[[-15,28],[15,28]]],microscope:[[[-34,38],[34,38]],[[-17,30],[8,18],[17,-8]],[[-4,-35],[20,-22],[7,1],[-16,-13],[-4,-35]],[[-27,28],[-14,6],[5,6]]],planet:[[[-38,2],[-20,-12],[7,-18],[32,-12],[40,0],[28,13],[0,19],[-28,12],[-38,2]],[[-46,-9],[-20,5],[14,9],[46,0]]],graph:[[[-38,36],[-38,-35]],[[-38,36],[38,36]],[[-31,22],[-12,5],[3,12],[30,-25]]],molecule:[[[-30,19],[0,-24],[31,19]],[[-30,19],[31,19]]],wave:[[[-42,5],[-28,-11],[-14,5],[0,21],[14,5],[28,-11],[42,5]]],mountain:[[[-45,35],[-13,-29],[3,-5],[18,-35],[45,35]],[[-23,1],[-13,-10],[-3,1]]],tree:[[[0,-43],[0,39]],[[-36,0],[0,-43],[36,0],[22,5],[39,29],[-39,29],[-22,5],[-36,0]]],eye:[[[-43,0],[-22,-19],[0,-25],[22,-19],[43,0],[22,19],[0,25],[-22,19],[-43,0]],[[-10,0],[0,-10],[10,0],[0,10],[-10,0]]],lightbulb:[[[-22,15],[-32,-3],[-25,-27],[0,-40],[25,-27],[32,-3],[22,15],[12,25],[-12,25],[-22,15]],[[-13,34],[13,34]]],heart:[[[0,36],[-36,0],[-31,-25],[-10,-35],[0,-20],[10,-35],[31,-25],[36,0],[0,36]]],question:[[[-24,-25],[-10,-40],[14,-38],[28,-22],[24,-3],[4,12],[2,24]],[[2,37],[2,39]]],cloud:[[[-40,17],[-35,-4],[-18,-12],[-8,-30],[13,-34],[27,-18],[41,-10],[43,12],[31,23],[-25,23],[-40,17]]],droplet:[[[0,-42],[-28,3],[-23,27],[0,40],[23,27],[28,3],[0,-42]]]};
function key(){return localStorage.getItem('gemini_api_key')||''} function status(s,e=false){$('#status').textContent=s;$('#status').style.color=e?'#ff8178':''}
function line(a,b,p){ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(a[0]+(b[0]-a[0])*p,a[1]+(b[1]-a[1])*p);ctx.stroke()}
function poly(points,p,closed=false){if(!points?.length)return;let n=points.length-1,z=Math.max(0,Math.min(n,p*n)),k=Math.floor(z),f=z-k;ctx.beginPath();ctx.moveTo(...points[0]);for(let i=1;i<=Math.min(k,n);i++)ctx.lineTo(...points[i]);if(k<n){let a=points[k],b=points[k+1];ctx.lineTo(a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f)}else if(closed)ctx.closePath();ctx.stroke()}
function circle(x,y,r,p=1){ctx.beginPath();ctx.arc(x,y,r,-Math.PI/2,-Math.PI/2+Math.PI*2*p);ctx.stroke()}
function person(o,p){let x=o.x,y=o.y,s=o.scale||1;circle(x,y-75*s,25*s,p);line([x,y-49*s],[x,y+34*s],p);line([x,y-15*s],[x-43*s,y+8*s],p);line([x,y-15*s],[x+43*s,y+8*s],p);line([x,y+34*s],[x-29*s,y+92*s],p);line([x,y+34*s],[x+29*s,y+92*s],p)}
function brain(o,p){ctx.save();ctx.translate(o.x,o.y);let pts=[];for(let i=0;i<32;i++){let a=i/31*Math.PI*2,r=(40+7*Math.sin(a*6))*(o.scale||1);pts.push([Math.cos(a)*r,Math.sin(a)*r*.72])}poly(pts,p,true);ctx.restore()}
function book(o,p){let x=o.x,y=o.y,s=o.scale||1;poly([[x-52*s,y-38*s],[x+52*s,y-38*s],[x+52*s,y+38*s],[x-52*s,y+38*s],[x-52*s,y-38*s]],p,true)}
function arrow(o,p){ctx.beginPath();ctx.arc(o.x,o.y,48*(o.scale||1),.2*Math.PI,(.2+1.55*p)*Math.PI);ctx.stroke()}
function icon(o,p){if(!icons[o.type])return false;ctx.save();ctx.translate(o.x,o.y);ctx.scale(o.scale||1,o.scale||1);icons[o.type].forEach((v,i)=>poly(v,Math.max(0,p-i*.07),i===0));ctx.restore();return true}
function textWrap(text,y,size){ctx.font=`600 ${size}px Pretendard,sans-serif`;ctx.textAlign='center';let s='',rows=[];for(let c of text){if(ctx.measureText(s+c).width>330){rows.push(s);s=c}else s+=c}rows.push(s);rows.slice(0,2).forEach((r,i)=>ctx.fillText(r,203,y+i*(size+7)))}
function free(strokes,p){(strokes||[]).slice(0,32).forEach((s,i)=>{let pts=(s.points||[]).slice(0,56).map(q=>[Math.max(32,Math.min(374,+q[0])),Math.max(120,Math.min(578,+q[1]))]);ctx.save();ctx.lineWidth=Math.max(.7,Math.min(2.5,+s.width||1.2));ctx.globalAlpha=Math.max(.15,Math.min(1,+s.opacity||.85));poly(pts,Math.max(0,Math.min(1,p*1.5-i*.022)),!!s.closed);ctx.restore()})}
function draw(t){let p=Math.max(0,Math.min(1,t/durationMs())),s=scene||fallback;ctx.fillStyle='#020202';ctx.fillRect(0,0,406,720);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#8c8b83';ctx.lineWidth=1.2;ctx.fillStyle='#111';ctx.fillRect(18,18,370,54);ctx.strokeStyle='#333';ctx.strokeRect(18,18,370,54);ctx.fillStyle='#f0efe9';textWrap(s.title||'',51,17);ctx.strokeStyle='#8c8b83';(s.objects||[]).slice(0,14).forEach((o,i)=>{let q=Math.max(0,Math.min(1,p*1.65-i*.045));if(icon(o,q))return;if(o.type==='person')person(o,q);else if(o.type==='brain')brain(o,q);else if(o.type==='book')book(o,q);else if(o.type==='arrow')arrow(o,q);else if(o.type==='dot'){circle(o.x,o.y,5*(o.scale||1),q);if(p>.65)circle(o.x,o.y,11*(o.scale||1),(p-.65)*3)}});free(s.strokes,p);ctx.globalAlpha=Math.min(1,p*3);ctx.fillStyle='#e9e8e1';textWrap(s.english||'',638,16);ctx.globalAlpha=.65;ctx.font='12px serif';ctx.fillText('science is not truth, science is a way.',203,686);ctx.globalAlpha=1}
function animate(){cancelAnimationFrame(raf);$('#playBtn').hidden=true;let st=performance.now(),d=durationMs();function f(n){let t=n-st;draw(t);if(t<d)raf=requestAnimationFrame(f);else $('#playBtn').hidden=false}raf=requestAnimationFrame(f)}
async function gemini(model,body){let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key())}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error?.message||'Gemini 호출 실패');return j}
async function make(again=false){let script=$('#script').value.trim(),sec=$('#duration').value;if(!script)return status('대본을 먼저 입력하세요.',true);if(!key()){openApi();return}status(again?'이전과 다른 복합 구도를 만드는 중입니다…':`${sec}초 복합 장면을 설계하는 중입니다…`);$('#makeBtn').disabled=$('#regenerateBtn').disabled=true;try{let prompt=`406x720 세로 과학 선화 영상의 한 장면을 JSON으로 설계하라. 길이 ${sec}초. 검정 배경과 가는 회색 연필선. 단순 아이콘 하나가 아니라 2~7개 요소가 관계를 이루는 복합 그림. 내장 type: person,brain,book,arrow,dot,atom,flask,beaker,testtube,dna,microscope,planet,graph,molecule,wave,mountain,tree,eye,lightbulb,heart,question,cloud,droplet. 부족한 인물 자세·동물·기관·기계·풍경은 strokes로 직접 그린다. strokes 각 항목은 points([[x,y], 최대56점),closed,width(0.7~2.5),opacity을 쓴다. 그림 영역 x 32~374,y 120~578. 그림 속 글자 금지. density=${$('#density').value}. ${again?'다음 이전 결과와 명백히 다른 구도여야 한다:'+JSON.stringify(scene):''} JSON 외에는 출력하지 않는다. schema={"title":"한국어 22자 이하","english":"짧은 영어","composition":"설명","objects":[{"type":"microscope","x":203,"y":350,"scale":1}],"strokes":[{"points":[[80,300],[120,260]],"closed":false,"width":1.2,"opacity":0.85}],"accent":"pulse"}. 대본: ${script}`;let j=await gemini('gemini-3.1-flash-lite',{contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:again?.92:.7,maxOutputTokens:8192}}),txt=j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';scene=JSON.parse(txt.replace(/^```json|```$/g,'').trim());$('#sceneJson').value=JSON.stringify(scene,null,2);$('#previewBtn').disabled=$('#downloadBtn').disabled=$('#regenerateBtn').disabled=false;status('복합 선화가 완성되었습니다. 그림만 다시 생성할 수도 있습니다.');draw(0);animate()}catch(e){if(!scene)scene=fallback;$('#sceneJson').value=JSON.stringify(scene,null,2);$('#previewBtn').disabled=$('#downloadBtn').disabled=false;status('생성에 실패했습니다: '+e.message,true);draw(0)}finally{$('#makeBtn').disabled=false;if(scene)$('#regenerateBtn').disabled=false}}
function openApi(){$('#apiKey').value=key();$('#apiDialog').showModal()}
async function audio(){if($('#voice').value==='none')return null;let sec=$('#duration').value,j=await gemini('gemini-3.1-flash-tts-preview',{contents:[{parts:[{text:`다음 문장을 자연스럽게 ${sec}초 안에 읽어주세요. ${$('#script').value.trim()}`}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:$('#voice').value}}}}}),part=j.candidates?.[0]?.content?.parts?.find(p=>p.inlineData);if(!part)return null;let bin=Uint8Array.from(atob(part.inlineData.data),c=>c.charCodeAt(0)),ac=new AudioContext(),pcm=new Int16Array(bin.buffer),buf=ac.createBuffer(1,pcm.length,24000),data=buf.getChannelData(0);for(let i=0;i<pcm.length;i++)data[i]=pcm[i]/32768;let src=ac.createBufferSource(),dest=ac.createMediaStreamDestination();src.buffer=buf;src.connect(dest);src.connect(ac.destination);return{src,stream:dest.stream}}
async function download(){if(!scene)return;let sec=$('#duration').value;status(`${sec}초 영상을 녹화하는 중입니다…`);$('#downloadBtn').disabled=true;try{let au=await audio().catch(()=>null),cs=C.captureStream(30),stream=new MediaStream([...cs.getVideoTracks(),...(au?au.stream.getAudioTracks():[])]),types=['video/mp4;codecs=h264,aac','video/webm;codecs=vp9,opus','video/webm'],mime=types.find(MediaRecorder.isTypeSupported)||'',rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4500000}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);let done=new Promise(r=>rec.onstop=r);rec.start();if(au)au.src.start();animate();await new Promise(r=>setTimeout(r,durationMs()+180));rec.stop();await done;let blob=new Blob(chunks,{type:rec.mimeType}),ext=rec.mimeType.includes('mp4')?'mp4':'webm',a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`science-sketch-${sec}s.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);status(`${ext.toUpperCase()} 영상이 다운로드되었습니다.`)}catch(e){status('녹화 실패: '+e.message,true)}finally{$('#downloadBtn').disabled=false}}
$('#apiBtn').onclick=openApi;$('#saveApi').onclick=()=>{localStorage.setItem('gemini_api_key',$('#apiKey').value.trim());status('API 키를 저장했습니다.')};$('#makeBtn').onclick=()=>make(false);$('#regenerateBtn').onclick=()=>make(true);$('#previewBtn').onclick=$('#playBtn').onclick=animate;$('#downloadBtn').onclick=download;$('#duration').onchange=()=>draw(0);$('#applyBtn').onclick=()=>{try{scene=JSON.parse($('#sceneJson').value);draw(0);status('수정 내용을 적용했습니다.')}catch{status('JSON 형식이 올바르지 않습니다.',true)}};draw(0);
