const $=s=>document.querySelector(s), C=$('#canvas'),ctx=C.getContext('2d');
const D=5000; let scene=null, playing=false, raf=0;
const fallback={title:'결과를 알고 나면',english:'Knowing the result changes the story.',composition:'person_connecting_dots',objects:[{type:'person',x:203,y:360,scale:1},{type:'dot',x:130,y:285},{type:'dot',x:205,y:240},{type:'dot',x:280,y:295}],accent:'connect',mood:'quiet'};
function key(){return localStorage.getItem('gemini_api_key')||''}
function roughLine(x1,y1,x2,y2,p){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x1+(x2-x1)*p,y1+(y2-y1)*p);ctx.stroke()}
function circle(x,y,r,p=1){ctx.beginPath();ctx.arc(x,y,r,-Math.PI/2,-Math.PI/2+Math.PI*2*p);ctx.stroke()}
function wrap(text,x,y,max,size,align='center'){ctx.font=`600 ${size}px Pretendard, sans-serif`;ctx.textAlign=align;let line='',rows=[];for(const ch of text){if(ctx.measureText(line+ch).width>max){rows.push(line);line=ch}else line+=ch}rows.push(line);rows.slice(0,2).forEach((r,i)=>ctx.fillText(r,x,y+i*(size+8)))}
function drawPerson(x,y,s,p){const q=Math.min(1,p*1.6);circle(x,y-76*s,26*s,q);roughLine(x,y-49*s,x,y+35*s,q);roughLine(x,y-15*s,x-45*s,y+6*s,q);roughLine(x,y-15*s,x+45*s,y+6*s,q);roughLine(x,y+35*s,x-30*s,y+94*s,q);roughLine(x,y+35*s,x+30*s,y+94*s,q)}
function drawBrain(x,y,s,p){ctx.beginPath();for(let i=0;i<22*p;i++){let a=i/21*Math.PI*2;let r=(42+7*Math.sin(a*5))*s;let xx=x+Math.cos(a)*r,yy=y+Math.sin(a)*r*.72;if(i===0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.stroke();roughLine(x,y-24*s,x,y+27*s,p)}
function drawBook(x,y,s,p){let w=105*s,h=78*s;roughLine(x-w/2,y-h/2,x+w/2,y-h/2,p);roughLine(x+w/2,y-h/2,x+w/2,y+h/2,p);roughLine(x+w/2,y+h/2,x-w/2,y+h/2,p);roughLine(x-w/2,y+h/2,x-w/2,y-h/2,p);roughLine(x-w/2+12,y-h/2,x-w/2+12,y+h/2,p)}
function drawArrow(x,y,s,p){ctx.beginPath();ctx.arc(x,y,50*s,Math.PI*.2,Math.PI*.2+Math.PI*1.55*p);ctx.stroke();if(p>.8){roughLine(x-46*s,y-18*s,x-59*s,y-2*s,(p-.8)*5);roughLine(x-46*s,y-18*s,x-25*s,y-14*s,(p-.8)*5)}}
function draw(t){let p=Math.max(0,Math.min(1,t/D));ctx.fillStyle='#020202';ctx.fillRect(0,0,C.width,C.height);ctx.strokeStyle='#8c8b83';ctx.fillStyle='#e7e6df';ctx.lineWidth=1.25;ctx.lineCap='round';ctx.lineJoin='round';ctx.globalAlpha=.92;ctx.fillStyle='#111';ctx.fillRect(18,18,370,54);ctx.strokeStyle='#333';ctx.strokeRect(18,18,370,54);ctx.fillStyle='#f2f1eb';wrap(scene?.title||fallback.title,203,51,330,17);ctx.strokeStyle='#8c8b83';(scene?.objects||fallback.objects).forEach((o,i)=>{let op=Math.max(0,Math.min(1,(p-i*.08)/.58));let s=o.scale||1;if(o.type==='person')drawPerson(o.x,o.y,s,op);else if(o.type==='brain')drawBrain(o.x,o.y,s,op);else if(o.type==='book')drawBook(o.x,o.y,s,op);else if(o.type==='arrow')drawArrow(o.x,o.y,s,op);else if(o.type==='dot'){circle(o.x,o.y,5*s,op);if(p>.55)circle(o.x,o.y,10*s,(p-.55)*2.2)}});if((scene?.accent||'connect')==='connect'&&p>.48){let ds=(scene?.objects||fallback.objects).filter(o=>o.type==='dot');for(let i=1;i<ds.length;i++)roughLine(ds[i-1].x,ds[i-1].y,ds[i].x,ds[i].y,Math.min(1,(p-.48)*3.2-i*.1))}ctx.globalAlpha=Math.min(1,p*3);ctx.fillStyle='#e9e8e1';wrap(scene?.english||fallback.english,203,638,330,16);ctx.globalAlpha=.7;ctx.font='12px serif';ctx.fillText('science is not truth, science is a way.',203,686);ctx.globalAlpha=1}
function animate(){cancelAnimationFrame(raf);playing=true;$('#playBtn').hidden=true;const start=performance.now();function f(now){let t=now-start;draw(t);if(t<D)raf=requestAnimationFrame(f);else{playing=false;$('#playBtn').hidden=false}}raf=requestAnimationFrame(f)}
async function gemini(model,body){let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key())}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Gemini 호출 실패');return j}
async function make(){let script=$('#script').value.trim();if(!script)return setStatus('대본을 먼저 입력하세요.',true);if(!key()){openApi();return}setStatus('대본에서 5초 장면을 설계하고 있습니다…');$('#makeBtn').disabled=true;try{let prompt=`당신은 세로형 과학 선화 영상 감독이다. 다음 한국어 대본을 정확히 5초 한 장면으로 바꿔라. 검정 배경, 가는 회색 연필선, 중앙 단일 상징, 과장 없는 미니멀 스타일. 사용 가능한 object type은 person, brain, book, arrow, dot뿐이다. 좌표 범위 x 70~336, y 170~530, scale 0.6~1.5. density=${$('#density').value}. 반드시 JSON만 출력한다. schema: {"title":"상단 한국어 22자 이하","english":"하단 짧은 영어 문장","composition":"설명","objects":[{"type":"person","x":203,"y":360,"scale":1}],"accent":"connect 또는 pulse","mood":"quiet"}. 대본: ${script}`;let j=await gemini('gemini-3.1-flash-lite',{contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.55}});let txt=j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';scene=JSON.parse(txt.replace(/^```json|```$/g,'').trim());$('#sceneJson').value=JSON.stringify(scene,null,2);draw(0);$('#previewBtn').disabled=$('#downloadBtn').disabled=false;setStatus('완성되었습니다. 미리보기로 확인한 뒤 다운로드하세요.');animate()}catch(e){console.error(e);scene=fallback;$('#sceneJson').value=JSON.stringify(scene,null,2);draw(0);$('#previewBtn').disabled=$('#downloadBtn').disabled=false;setStatus(`Gemini 응답을 읽지 못해 기본 장면을 표시했습니다: ${e.message}`,true)}finally{$('#makeBtn').disabled=false}}
function setStatus(s,err=false){$('#status').textContent=s;$('#status').style.color=err?'#ff8178':''}
function openApi(){$('#apiKey').value=key();$('#apiDialog').showModal()}
async function ttsStream(){if($('#voice').value==='none')return null;let j=await gemini('gemini-3.1-flash-tts-preview',{contents:[{parts:[{text:`다음 문장을 자연스럽게 5초 이내로 읽어주세요. ${$('#script').value.trim()}`}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:$('#voice').value}}}}});let part=j.candidates?.[0]?.content?.parts?.find(p=>p.inlineData);if(!part)return null;let bin=Uint8Array.from(atob(part.inlineData.data),c=>c.charCodeAt(0));let ac=new AudioContext(),rate=24000,pcm=new Int16Array(bin.buffer),buf=ac.createBuffer(1,pcm.length,rate);let data=buf.getChannelData(0);for(let i=0;i<pcm.length;i++)data[i]=pcm[i]/32768;let src=ac.createBufferSource(),dest=ac.createMediaStreamDestination();src.buffer=buf;src.connect(dest);src.connect(ac.destination);return{ac,src,stream:dest.stream}}
async function download(){if(!scene)return;setStatus('5초 영상을 녹화하고 있습니다…');$('#downloadBtn').disabled=true;try{let ts=await ttsStream().catch(()=>null),cs=C.captureStream(30),tracks=[...cs.getVideoTracks(),...(ts?ts.stream.getAudioTracks():[])];let stream=new MediaStream(tracks);let types=['video/mp4;codecs=h264,aac','video/webm;codecs=vp9,opus','video/webm'];let mime=types.find(MediaRecorder.isTypeSupported)||'';let rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4500000}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);let done=new Promise(r=>rec.onstop=r);rec.start();if(ts)ts.src.start();animate();await new Promise(r=>setTimeout(r,D+180));rec.stop();await done;let blob=new Blob(chunks,{type:rec.mimeType}),ext=rec.mimeType.includes('mp4')?'mp4':'webm',a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`science-sketch-5s.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);setStatus(`${ext.toUpperCase()} 영상이 다운로드되었습니다.`)}catch(e){setStatus(`녹화에 실패했습니다: ${e.message}`,true)}finally{$('#downloadBtn').disabled=false}}
$('#apiBtn').onclick=openApi;$('#saveApi').onclick=()=>{localStorage.setItem('gemini_api_key',$('#apiKey').value.trim());setStatus('API 키를 저장했습니다.')};$('#makeBtn').onclick=make;$('#previewBtn').onclick=animate;$('#playBtn').onclick=animate;$('#downloadBtn').onclick=download;$('#applyBtn').onclick=()=>{try{scene=JSON.parse($('#sceneJson').value);draw(0);setStatus('수정한 장면을 적용했습니다.')}catch{setStatus('JSON 형식이 올바르지 않습니다.',true)}};draw(0);
